name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run Test
        run: cargo test

      - name: Test Chrome
        run: wasm-pack test --headless --chrome

      - name: Test Firefox
        run: wasm-pack test --headless --firefox
